version: '3.7'

services:
  resilio-sync:
    image: linuxserver/resilio-sync:latest
    container_name: resilio-sync
    networks:
      - web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ../../cloud-data/resilio-sync/config:/config
      - ../../cloud-data/resilio-sync/data:/sync
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.resilio.loadbalancer.server.port=8888

      # HTTPS
      - traefik.http.routers.resilio.rule=Host(`resilio.${CLOUD_DOMAIN}`)
      - traefik.http.routers.resilio.tls.certresolver=mytlschallenge
      - traefik.http.routers.resilio.entrypoints=web-secured
      - traefik.http.routers.resilio.tls=true
      - traefik.http.routers.resilio.service=resilio

networks:
  web:
    external: true
